config/routes.rb
Website::Application.routes.draw do
  resources :recipes do
    resources :ingredients
  end

  resources :wedding, :recipes, :guests

  root 'wedding#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe

 before_create :downcase

  private
    def downcase
      self.ingredient.downcase!
      self.unit.downcase!
     end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 #  before_filter :add_cors_headers

	# def add_cors_headers
	#   origin = request.headers["Origin"]
	#   unless (not origin.nil?) and (origin == "http://127.0.0.1:3000/recipes.json")
	#     origin == "http://127.0.0.1:3000/recipes.json"
	#   end
	#   headers['Access-Control-Allow-Origin'] = origin
	#   headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS, PUT, DELETE'
	#   allow_headers = request.headers["Access-Control-Request-Headers"]
	#   if allow_headers.nil?
	#     #shouldn't happen, but better be safe
	#     allow_headers = 'Origin, Authorization, Accept, Content-Type'
	#   end
	#   headers['Access-Control-Allow-Headers'] = allow_headers
	#   headers['Access-Control-Allow-Credentials'] = 'true'
	#   headers['Access-Control-Max-Age'] = '1728000'
	# end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

	def update
		@guest = Guest.find(params[:id])
		@guest.update(params[:guest].permit(:attend))
		#@guest.update
		redirect_to wedding_path
	end

	def nap
		@guest = Guest.find(params[:id])
		@guest.update_attribute(:name, 'pollo')
	end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    #render :text => (params[:recipe_id])
    @ingredient = @recipe.ingredients.create(ingredient_params)
    redirect_to recipe_path(@recipe)
  end
 
  private
    def ingredient_params
      params.require(:ingredient).permit(:ingredient, :amount, :unit)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]



  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
  

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :recipe_type, :description, :img_url, :preparation)
    end
end

app/controllers/wedding_controller.rb
class WeddingController < ApplicationController
	def index
	end

	def show
		@guests = Guest.all
		@guests.each do |x|
			name = x.name
			attend = x.attend
		end
	end

	def change_attend
		
	end

	def edit
		@guest = Guest.find(params[:id])
		flash[:notice] = 'pollo' 
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/wedding_helper.rb
module WeddingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<head>
  <title>Website</title>

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %> 
  <link href="/assets/bootstrap.css?body=1" media="screen" rel="stylesheet">

</head>

<body>

<%= render '/wedding/navigation' %>
<div class='container'>

	<%= yield %>

</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>

</body>
</html>

app/views/layouts/not-used-wedding.html.erb
<%= render 'navigation' %>  

app/views/pages/wedding/ceremoniemeester.html.erb
ceremoniemeester

app/views/pages/wedding/location.html.erb
<div class="container">
  <div class="page-header">
    <h1>De Zwarte Boer</h1>
  </div>
</div>

<!--Jumbotron-->
<div class="container">
  <div class="row">
    <div class='col-md-6'>
      <div class='thumbnail'>
        <img src='http://upload.wikimedia.org/wikipedia/commons/b/b7/De_Zwarte_Boer_Leuvenum.jpg' >
      <h3>Boutique Hotel-Restaurant De Zwarte Boer</h3>
      <p>Het decor van onze bruiloft is een van de kleinste 4 sterren hotels van Nederland.</p>
      <p>De geschiedenis van De Zwarte Boer gaat terug tot het jaar 1600. Gelegen aan de oude Hessenwegen heeft De Zwarte Boer zich reeds 408 jaar mogen verheugen op het verwelkomen van koetsiers van diligences en handelsreizigers. Nu verwelkomen wij jullie!</p>
      <p>Bij binnenkomst proeft u direct de roemrijke geschiedenis. De oude togen, antieke kroonluchters, haard, kasten, spanten -en vloeren doen u 400 jaar terug gaan in de tijd.</p>
      <p>De Zwarte Boer is gelegen op het schitterende Landgoed Leuvenum. De prachtige natuur nodigt uit tot wandelen en fietsen. Onze restaurants bieden voor iedere gelegenheid de juiste mogelijkheden.</p>
    </div>
  </div>
  <div class='col-md-6'>
    <div class='thumbnail'>
      <div class="page-header">
        <h3>Routebeschrijving naar De Zwarte Boer</h3>
      </div>
      <div class="Flexible-container">
        <!-- Responsive iFrame voor Google Maps-->
          <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d78032.59034915632!2d5.688825469652762!3d52.32474013213571!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c7cb510f7e0deb%3A0x8bc9f63203efa036!2sDe+Zwarte+Boer!5e0!3m2!1snl!2snl!4v1399327091331" width="600" height="450" frameborder="0" style="border:0"></iframe>
        </div>
      </div>
  </div>
  </div>
</div>


</div>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :recipe_type %><br>
    <%= f.text_field :recipe_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :preparation %><br>
    <%= f.text_area :preparation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>


<div class="table-responsive">
  <table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Recipe type</th>
      <th>Description</th>
      <th>Preparation</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.recipe_type %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.preparation %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></button></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

<p><a class="btn btn-primary btn-lg" href="/recipes/new">Nieuw Recept</a></p>

<% link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Recipe type:</strong>
  <%= @recipe.recipe_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @recipe.img_url %>
</p>

<p>
  <strong>Preparation:</strong>
  <%= @recipe.preparation %>
</p>

<h2>Ingredients</h2>
<% @recipe.ingredients.each do |ingredient| %>
  <p>
    <%= ingredient.ingredient.capitalize %>  <%= ingredient.amount %> <%= ingredient.unit %>
  </p>


<% end %>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/wedding/_footer.html.erb
<!--Footer-->
<div class="navbar navbar-default navbar-static-bottom">
  <div class="container">
    <p class="navbar-text pull-left">The wedding site</p>
    <a href="http://www.nu.nl" class="navbar-btn btn-danger btn pull-right">Lees meer</a>
  </div>
</div>

app/views/wedding/_navigation.html.erb
<!-- Navigation -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <a href="/wedding" class="navbar-brand">De Bruiloft</a>
    <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse navHeaderCollapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/wedding">Home</a></li>
        <li><a href="/pages/wedding/location">Locatie</a></li>
        <li><a href="/pages/wedding/ceremoniemeester">Ceremoniemeester</a></li>
        <li><a href="/wedding/guests">Gasten</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gast informatie<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="/wedding/fotos">Foto's</a></li>
            <li><a href="/wedding/kadotips">Kado tips</a></li>
            <li><a href="/wedding/overnachten">Overnachten</a></li>
          </ul>
        </li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/wedding/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1><%= @guest.name %></h1>
  </div>

    <%= form_for @guest do |f| %>
    <p>
        <%= f.label :Aanwezigheid %><br><br>
        <%= f.radio_button :attend, true %> Ik kom <br><br>
        <%= f.radio_button :attend, false %> Ik kom niet<br><br>
      </p>
     
      <p>
        <%= f.submit 'Update'%>
      </p>
      </tr>
    <% end %>




</div>

app/views/wedding/index.html.erb
<!-- Carousel -->
<div class="container">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
<!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
<!-- Wrapper for slides -->
<div class="carousel-inner">
<div class="item active">
  <%= image_tag 'wedding/champagne.jpg' %>
  <div class="carousel-caption">
    <h1>Jewelry</h1>
    <p>...</p>
  </div>
</div>
<div class="item">
  <img src="http://www.kingsheadwye.com/wp-content/uploads/2012/10/KHdrink1.jpg" alt="...">
  <div class="carousel-caption">
    <h3>Drinks</h3>
    <p>...</p>
  </div>
</div>
<div class="item">
  <img src="http://www.crawlmiami.com/wp-content/uploads/2013/10/pageheader.jpg" alt="...">
  <div class="carousel-caption">
    <h3>Party</h3>
    <p>...</p>
  </div>
</div>
</div>
<!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>
</div>

<!--Test met images-->
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="thumbnail">
      <%= image_tag 'wedding/de_zwarte_boer.png' %>
        <div class="caption">
          <h3>De Zwarte Boer</h3>
          <p>In het pittoreske Leuvenum ligt midden in de bossen het kleinste 4 sterren hotel van Nederland.</p>
          <div class='text-center'>
          <p><a href="location" class="btn btn-primary" role="button" btn-pull-right>Meer info</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="thumbnail">
      <img src="http://www.letsgodigital.org/images/producten/340/specs/canon_eos_10d_front.jpg" alt="...">
        <div class="caption">
          <h3>Foto's</h3>
          <p>We zouden het leuk vinden als zoveel mogelijk mensen fotos maken. Neem je camera dus mee!</p>
          <div class='text-center'>
          <p><a href="location" class="btn btn-primary" role="button" btn-pull-right>Meer info</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="thumbnail">
      <img src="http://cdn.kveller.com/blog/wp-content/uploads/2011/11/Hanukkah-presents-300x200.jpg" alt="...">
        <div class="caption">
          <h3>Kado Tips</h3>
          <p>Wat willen we echt graag hebben. Kijk hier voor een lijstje van zaken die we graag ontvangen.</p>
          <div class='text-center'>
          <p><a href="location" class="btn btn-primary" role="button" btn-pull-right>Meer info</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="thumbnail">
      <img src="http://www.kontaktderkontinenten.nl/Images/Foto_kamers/hotelkamer-210_200x300_2910.aspx" alt="...">
        <div class="caption">
          <h3>Overnachten</h3>
          <p>Leuvenum is niet voor iedereen naast de deur. Hier enkele tips voor wie wil overnachten.</p>
          <div class='text-center'>
          <p><a href="location" class="btn btn-primary" role="button" btn-pull-right>Meer info</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/wedding/save-show.html.erb
<div class="container">
  <div class="page-header">
    <h1>Gasten</h1>
  </div>
</div>


	<div class='row'>
		<div class='col-sm-4'>
			<table class="table table-striped">
			<th>Naam</th>
			<th>Aanwezig <span class="glyphicon glyphicon-info-sign"></span></th>
			<% @guests.each do |guest| %>
				<tr>
					<td><a href="#"> <%= guest.name %> </a></td>
					<td>
					<% if guest.attend == true %>
						<% btn_color = "btn btn-success" %>
						<% btn_color_dif = "btn btn-default"%>
						<% attending = "Ja"%>
						<% attending_dif = "Nee" %>
					<% else %>
						<% btn_color = "btn btn-warning" %>
						<% btn_color_dif = "btn btn-warning "%>
						<% attending = "Nee"%>
						<% attending_dif = "Ja" %>
					<% end %>
					<!-- Split button -->
					<div class="btn-group">
					  <button type="button" class="<%= btn_color %> dropdown-toggle" data-toggle="dropdown"><%= attending %>
					    <span class="caret"></span>
		
					  </button>
					  <ul class="dropdown-menu" role="menu">
					    <li><a href="/pages/wedding/location"><%= attending_dif %></a></li>
					  </ul>
					</div>
					</td>
				</tr>
			<% end %>
			</table>
		</div>
	</div>






	

app/views/wedding/show.html.erb
<div class="container">
  <div class="page-header">
    <h1>Gasten</h1>
  </div>
</div>

<%= stylesheet_link_tag "guests", media: "all", "data-turbolinks-track" => true %>

	<div class='row'>
		<div class='col-sm-4'>
			<table class="table table-striped">
			<th>ID</th>
			<th>Naam</th>
			<th>Aanwezig <span class="glyphicon glyphicon-info-sign" data-toggle="modal" data-target="#myModal"> </span></th>
			<th>Edit</th>
			<% @guests.each do |guest| %>
				<tr>
					<td><%= guest.id %> </a></td>
					<td><%= guest.name %> </a></td>
					<td>
					<% if guest.attend == true %>
						<% btn_color = "btn btn-success" %>
						<% btn_color_dif = "btn btn-default"%>
						<% attending = "Ja"%>
						<% attending_dif = "Nee" %>
					<% else %>
						<% btn_color = "btn btn-warning" %>
						<% btn_color_dif = "btn btn-warning "%>
						<% attending = "Nee"%>
						<% attending_dif = "Ja" %>
					<% end %>
					<!-- Split button -->
					<div class="btn-group">
					  <button type="button" class="<%= btn_color %> dropdown-toggle" data-toggle="dropdown"><%= attending %>
					    <span class="caret"></span>
		
					  </button>
					  <ul class="dropdown-menu" role="menu">
					    <li><%= link_to 'Pas aanwezigheid aan', edit_wedding_path(guest.id) %></a></li>
					  </ul>
					</div>
					</td>
					<td><%= link_to 'Edit', edit_wedding_path(guest.id) %></td>
				</tr>
			<% end %>
			</table>
		</div>
	</div>



  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Aanwezigheid</h4>
        </div>
        <div class="modal-body">
          Hier kun je aanpassen of je verwacht wel of niet te komen. Mocht dit later wijzigen, dan kan dit altijd nog. Maar het geeft een ons beeld hoeveel mensen er komen. Zo kunnen we rekening houden met bijvoorbeeld genoeg drankjes. 
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome</h1>